#!/usr/bin/env python3
"""
PhotoVault Railway Setup Script
Copyright (c) 2025 Calmic Sdn Bhd. All rights reserved.

This script helps set up PhotoVault for Railway deployment with Supabase.
"""

import os
import sys
import subprocess
import secrets
import urllib.parse
from pathlib import Path

def print_banner():
    print("""
╔══════════════════════════════════════════════════════════════╗
║                        PhotoVault                            ║
║                   Railway Setup Script                      ║
║                                                              ║
║                   by Calmic Sdn Bhd                         ║
║                "Committed to Excellence"                     ║
╚══════════════════════════════════════════════════════════════╝
    """)

def check_requirements():
    """Check if required tools are installed."""
    print("🔍 Checking requirements...")
    
    # Check Python version
    if sys.version_info < (3, 8):
        print("❌ Python 3.8+ is required")
        return False
    
    print(f"✅ Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")
    
    # Check if git is available
    try:
        subprocess.run(['git', '--version'], capture_output=True, check=True)
        print("✅ Git is available")
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("⚠️  Git not found (optional)")
    
    # Check if railway CLI is available
    try:
        subprocess.run(['railway', '--version'], capture_output=True, check=True)
        print("✅ Railway CLI is available")
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("⚠️  Railway CLI not found (install from https://docs.railway.app/develop/cli)")
    
    return True

def generate_secret_key():
    """Generate a secure secret key."""
    return secrets.token_urlsafe(32)

def validate_database_url(url):
    """Validate database URL format."""
    try:
        parsed = urllib.parse.urlparse(url)
        if parsed.scheme not in ['postgresql', 'postgres']:
            return False, "Database URL must start with postgresql:// or postgres://"
        
        if not parsed.hostname:
            return False, "Database URL must include hostname"
        
        if 'supabase.co' not in parsed.hostname:
            return False, "Expected Supabase database URL"
        
        return True, "Valid database URL"
    except Exception as e:
        return False, f"Invalid URL format: {str(e)}"

def create_env_file():
    """Create .env file with user input."""
    print("\n🛠️  Setting up environment variables...")
    
    env_file = Path('.env')
    env_vars = {}
    
    # Secret key
    print("\n1. Generate SECRET_KEY:")
    secret_key = generate_secret_key()
    env_vars['SECRET_KEY'] = secret_key
    print(f"✅ Generated: {secret_key[:16]}...")
    
    # Database URL
    print("\n2. Supabase Database Setup:")
    print("   Go to https://supabase.com/dashboard")
    print("   Create a new project or use existing")
    print("   Go to Settings → Database")
    print("   Copy the connection string (URI format)")
    
    while True:
        db_url = input("\nEnter your Supabase DATABASE_URL: ").strip()
        if not db_url:
            print("❌ Database URL is required")
            continue
        
        # Convert postgres:// to postgresql://
        if db_url.startswith('postgres://'):
            db_url = db_url.replace('postgres://', 'postgresql://', 1)
        
        is_valid, message = validate_database_url(db_url)
        if is_valid:
            env_vars['DATABASE_URL'] = db_url
            print("✅ Database URL validated")
            break
        else:
            print(f"❌ {message}")
    
    # Supabase configuration
    print("\n3. Supabase API Configuration:")
    print("   Go to Settings → API in your Supabase project")
    
    supabase_url = input("Enter your SUPABASE_URL: ").strip()
    if supabase_url:
        env_vars['SUPABASE_URL'] = supabase_url
        print("✅ Supabase URL set")
    
    anon_key = input("Enter your SUPABASE_ANON_KEY: ").strip()
    if anon_key:
        env_vars['SUPABASE_ANON_KEY'] = anon_key
        print("✅ Anon key set")
    
    service_key = input("Enter your SUPABASE_SERVICE_ROLE_KEY (optional): ").strip()
    if service_key:
        env_vars['SUPABASE_SERVICE_ROLE_KEY'] = service_key
        print("✅ Service role key set")
    
    # Flask environment
    env_vars['FLASK_ENV'] = 'production'
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# PhotoVault Environment Variables\n")
        f.write("# Generated by Railway setup script\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print(f"✅ Environment file created: {env_file}")
    return env_vars

def setup_railway_project():
    """Set up Railway project."""
    print("\n🚂 Railway Project Setup:")
    
    try:
        # Check if already linked
        result = subprocess.run(['railway', 'status'], capture_output=True, text=True)
        if result.returncode == 0:
            print("✅ Already linked to Railway project")
            return True
    except FileNotFoundError:
        print("❌ Railway CLI not found. Install from https://docs.railway.app/develop/cli")
        return False
    
    # Login to Railway
    print("1. Logging in to Railway...")
    try:
        subprocess.run(['railway', 'login'], check=True)
        print("✅ Logged in to Railway")
    except subprocess.CalledProcessError:
        print("❌ Failed to login to Railway")
        return False
    
    # Create or link project
    create_new = input("Create new Railway project? (y/N): ").lower().startswith('y')
    
    if create_new:
        project_name = input("Enter project name (default: photovault): ").strip() or "photovault"
        try:
            subprocess.run(['railway', 'init', project_name], check=True)
            print(f"✅ Created Railway project: {project_name}")
        except subprocess.CalledProcessError:
            print("❌ Failed to create Railway project")
            return False
    else:
        try:
            subprocess.run(['railway', 'link'], check=True)
            print("✅ Linked to existing Railway project")
        except subprocess.CalledProcessError:
            print("❌ Failed to link to Railway project")
            return False
    
    return True

def set_railway_variables(env_vars):
    """Set environment variables in Railway."""
    print("\n📝 Setting Railway environment variables...")
    
    try:
        for key, value in env_vars.items():
            print(f"Setting {key}...")
            subprocess.run(['railway', 'variables', 'set', f'{key}={value}'], check=True)
        
        print("✅ All environment variables set in Railway")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to set Railway variables: {e}")
        return False
    except FileNotFoundError:
        print("❌ Railway CLI not found")
        return False

def deploy_to_railway():
    """Deploy to Railway."""
    print("\n🚀 Deploying to Railway...")
    
    try:
        # Deploy
        subprocess.run(['railway', 'up'], check=True)
        print("✅ Deployed to Railway successfully")
        
        # Get domain
        result = subprocess.run(['railway', 'domain'], capture_output=True, text=True)
        if result.returncode == 0 and result.stdout.strip():
            domain = result.stdout.strip()
            print(f"🌐 Your app is available at: {domain}")
        
        return True
    except subprocess.CalledProcessError:
        print("❌ Deployment failed")
        return False
    except FileNotFoundError:
        print("❌ Railway CLI not found")
        return False

def run_initial_setup():
    """Run initial setup commands."""
    print("\n⚙️  Running initial setup...")
    
    try:
        # Create superuser
        print("Creating initial superuser...")
        subprocess.run(['railway', 'run', 'flask', 'create-superuser'], check=True)
        print("✅ Superuser created")
        
        # Check status
        subprocess.run(['railway', 'run', 'flask', 'check-db'], check=True)
        print("✅ Database connection verified")
        
        return True
    except subprocess.CalledProcessError:
        print("⚠️  Initial setup had some issues, but deployment should still work")
        print("   You can create a superuser later via the Railway dashboard")
        return True
    except FileNotFoundError:
        print("❌ Railway CLI not found for initial setup")
        return False

def main():
    """Main setup process."""
    print_banner()
    
    if not check_requirements():
        sys.exit(1)
    
    print("\n🎯 PhotoVault Railway Deployment Setup")
    print("This script will help you deploy PhotoVault to Railway with Supabase.\n")
    
    # Step 1: Environment variables
    env_vars = create_env_file()
    
    # Step 2: Railway setup
    if not setup_railway_project():
        print("\n❌ Railway setup failed. You can continue manually.")
        print("   1. Install Railway CLI: https://docs.railway.app/develop/cli")
        print("   2. Run: railway login")
        print("   3. Run: railway init")
        print("   4. Set environment variables manually in Railway dashboard")
        return
    
    # Step 3: Set variables
    if not set_railway_variables(env_vars):
        print("\n⚠️  Failed to set variables automatically.")
        print("   Please set these variables manually in your Railway dashboard:")
        for key, value in env_vars.items():
            if 'SECRET' in key or 'KEY' in key:
                print(f"   {key}={value[:10]}...")
            else:
                print(f"   {key}={value}")
        return
    
    # Step 4: Deploy
    if not deploy_to_railway():
        print("\n❌ Deployment failed. Please check Railway dashboard for details.")
        return
    
    # Step 5: Initial setup
    run_initial_setup()
    
    print("\n🎉 PhotoVault setup completed successfully!")
    print("\n📋 Next steps:")
    print("   1. Visit your Railway app URL")
    print("   2. Create your first user account (or use the superuser)")
    print("   3. Upload and manage your photos")
    print("   4. Configure custom domain if needed")
    print("\n📞 Support:")
    print("   - PhotoVault: Calmic Sdn Bhd")
    print("   - Railway: https://docs.railway.app")
    print("   - Supabase: https://supabase.com/docs")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n👋 Setup cancelled by user")
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        sys.exit(1)